// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeWyh2ctHZ6vDceaNCCPMt0dGNkXKir4E',
    appId: '1:979720031953:web:44c65ad74914b24900fff0',
    messagingSenderId: '979720031953',
    projectId: 'adv-flutter-app-distribution',
    authDomain: 'adv-flutter-app-distribution.firebaseapp.com',
    storageBucket: 'adv-flutter-app-distribution.appspot.com',
    measurementId: 'G-37DD4GR4S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlqNqCFlz-mb4zeQEQdUdwzy8iJNQ_fm8',
    appId: '1:979720031953:android:a9bf46cac8eb0b8900fff0',
    messagingSenderId: '979720031953',
    projectId: 'adv-flutter-app-distribution',
    storageBucket: 'adv-flutter-app-distribution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALvOD8GNy4qW2Z4Ixs3wHGvmO-etu5Syg',
    appId: '1:979720031953:ios:6bf5300e962bfc1300fff0',
    messagingSenderId: '979720031953',
    projectId: 'adv-flutter-app-distribution',
    storageBucket: 'adv-flutter-app-distribution.appspot.com',
    iosBundleId: 'com.example.flutterAdvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALvOD8GNy4qW2Z4Ixs3wHGvmO-etu5Syg',
    appId: '1:979720031953:ios:6bf5300e962bfc1300fff0',
    messagingSenderId: '979720031953',
    projectId: 'adv-flutter-app-distribution',
    storageBucket: 'adv-flutter-app-distribution.appspot.com',
    iosBundleId: 'com.example.flutterAdvApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeWyh2ctHZ6vDceaNCCPMt0dGNkXKir4E',
    appId: '1:979720031953:web:b11b5f44ec80858800fff0',
    messagingSenderId: '979720031953',
    projectId: 'adv-flutter-app-distribution',
    authDomain: 'adv-flutter-app-distribution.firebaseapp.com',
    storageBucket: 'adv-flutter-app-distribution.appspot.com',
    measurementId: 'G-ZCJ1VPR3CK',
  );
}
