# # Fastlanw with GitHub Actions using ruby
# # any name for the file
# name: Android Fastlane with Firebase App Distribution Workflow

# # this workflow will work on master branch
# on:
#   push:
#     branches:
#       - master

# jobs:
#   # distribute_to_firebase is optional name from GitHub
#   distribute_to_firebase:
#     # ubuntu-latest bc will distribute android package
#     runs-on: ubuntu-latest
#     steps:
#       # name is optional as comment
#       - name: Checkout my repo code
#         uses: actions/checkout@v2

#       - name: Set up JDK 11
#         uses: actions/setup-java@v2
#         with:
#           java-version: "11"
#           distribution: "temurin"

#       - name: Install Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: "3.2.3"
#           bundler-cache: true
#           working-directory: android

#       - name: Build and Distribute App
#         env:
#           FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
#         run: |
#           bundle exec fastlane android firebase_distribution
#         working-directory: android
